site_name: SHAPEwarp
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
pages:
    - 'Overview': 'index.md'
    - 'SHAPEwarp': 'SHAPEwarp.md'
    - 'swBuildDb': 'swBuildDb.md'
    - 'swKmerLookup': 'swKmerLookup.md'
    - 'Application case': 'case.md'
markdown_extensions:
    - markdown.extensions.admonition
