site_name: SHAPEwarp
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
pages:
    - 'Overview': 'index.md'
    - 'SHAPEwarp': 'SHAPEwarp.md'
    - 'Application case': 'case.md'
markdown_extensions:
    - markdown.extensions.admonition
